// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooVrt.Persistance.Database;

namespace ZooVrt.Persistance.Migrations
{
    [DbContext(typeof(ZooVrtContext))]
    [Migration("20210322200123_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZooVrt.Domain.Entities.Lokacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StanisteId")
                        .HasColumnType("int");

                    b.Property<string>("Vrsta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Zbir")
                        .HasColumnType("int");

                    b.Property<int>("ZooVrtId")
                        .HasColumnType("int");

                    b.Property<int?>("ZooVrtId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StanisteId");

                    b.HasIndex("ZooVrtId");

                    b.HasIndex("ZooVrtId1");

                    b.ToTable("Lokacije");
                });

            modelBuilder.Entity("ZooVrt.Domain.Entities.TipStanista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoviStanista");
                });

            modelBuilder.Entity("ZooVrt.Domain.Entities.ZooVrt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<int>("M")
                        .HasColumnType("int");

                    b.Property<int>("N")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ZooVrt");
                });

            modelBuilder.Entity("ZooVrt.Domain.Entities.Lokacija", b =>
                {
                    b.HasOne("ZooVrt.Domain.Entities.TipStanista", "Staniste")
                        .WithMany()
                        .HasForeignKey("StanisteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZooVrt.Domain.Entities.ZooVrt", "ZooVrt")
                        .WithMany()
                        .HasForeignKey("ZooVrtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooVrt.Domain.Entities.ZooVrt", null)
                        .WithMany("Lokacije")
                        .HasForeignKey("ZooVrtId1");
                });
#pragma warning restore 612, 618
        }
    }
}
